title: Jing's Blog
author: Jing Zhou
email: jzhou0604@gmail.com

# social links
github_username:  jzihnogu # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: dinky
